services:
  - type: web
    name: ain-backend-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r render-requirements.txt && ./postinstall.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        value: language-generation
      - key: GOOGLE_CLOUD_LOCATION
        value: us-central1
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
