services:
  - type: web
    name: ain-backend-api
    env: python
    buildCommand: pip install -r render-requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
