[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel", "gcc", "ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt", "python -m spacy download en_core_web_sm"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
